// Auto-generated by routeGen.py — beds routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getBedcontrollers, createBedcontroller, getBedcontroller, updateBedcontroller, deleteBedcontroller } from "../controllers/bedController.js";
import { getBedAvailability } from "../controllers/availabilityController.js";
import { createBedSchema } from "../validations/bedValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getBedcontrollers)
  .post(validate(createBedSchema), createBedcontroller);

router.route("/:id").get(getBedcontroller).patch(updateBedcontroller).delete(deleteBedcontroller);

router.get("/:id/availability", getBedAvailability);
export default router;
