// Auto-generated by routeGen.py — billing runs routes
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";
import { createBillingRun, previewBillingRun, getBillingRun } from "../controllers/billingRunController.js";
import { billingRunSchema } from "../validations/billingRunValidation.js";

const router = express.Router();
router.use(protect);

router.post("/", validate(billingRunSchema), createBillingRun);
router.post("/preview", validate(billingRunSchema), previewBillingRun);
router.get("/:id", getBillingRun);

export default router;
