// Auto-generated by routeGen.py — bills routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getBillcontrollers, createBillcontroller, getBillcontroller, updateBillcontroller, deleteBillcontroller } from "../controllers/billController.js";
import { getBillSummary, recalculateBill, markBillPaid } from "../controllers/billController.js";
import { createBillSchema } from "../validations/billValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getBillcontrollers)
  .post(validate(createBillSchema), createBillcontroller);

router.route("/:id").get(getBillcontroller).patch(updateBillcontroller).delete(deleteBillcontroller);

router.get("/:id/summary", getBillSummary);
router.post("/:id/recalculate", recalculateBill);
router.post("/:id/mark-paid", markBillPaid);
export default router;
