// Auto-generated by routeGen.py — dashboards routes
import express from "express";
import { protect } from "../middlewares/auth.js";
import { tenantDashboard } from "../controllers/dashboardController.js";

const router = express.Router();
router.use(protect);

router.get("/tenant/:tenantId", tenantDashboard);

export default router;
