// Auto-generated by routeGen.py — documents routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getDocumentcontrollers, createDocumentcontroller, getDocumentcontroller, updateDocumentcontroller, deleteDocumentcontroller } from "../controllers/documentController.js";
import { createDocumentSchema } from "../validations/documentValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getDocumentcontrollers)
  .post(validate(createDocumentSchema), createDocumentcontroller);

router.route("/:id").get(getDocumentcontroller).patch(updateDocumentcontroller).delete(deleteDocumentcontroller);

export default router;
