// Auto-generated by routeGen.py — routes index
import express from "express";

import authRoutes from "./auth.js";
import pgRoutes from "./pgs.js";
import roomRoutes from "./rooms.js";
import bedRoutes from "./beds.js";
import tenantRoutes from "./tenants.js";
import occupancyRoutes from "./occupancies.js";
import billRoutes from "./bills.js";
import transactionRoutes from "./transactions.js";
import documentRoutes from "./documents.js";
import tenantDocumentRoutes from "./tenantDocuments.js";
import billingRunRoutes from "./billingRuns.js";
import reportRoutes from "./reports.js";
import dashboardRoutes from "./dashboards.js";
import searchRoutes from "./search.js";

const router = express.Router();

// Public-ish
router.use("/auth", authRoutes);

// Protected groups (each subrouter handles protect)
router.use("/pgs", pgRoutes);
router.use("/rooms", roomRoutes);
router.use("/beds", bedRoutes);
router.use("/tenants", tenantRoutes);
router.use("/occupancies", occupancyRoutes);
router.use("/bills", billRoutes);
router.use("/transactions", transactionRoutes);
router.use("/documents", documentRoutes);
router.use("/tenant-documents", tenantDocumentRoutes);
router.use("/billing/runs", billingRunRoutes);
router.use("/reports", reportRoutes);
router.use("/dashboards", dashboardRoutes);
router.use("/search", searchRoutes);

export default router;
