// Auto-generated by routeGen.py — occupancies routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getOccupancycontrollers, createOccupancycontroller, getOccupancycontroller, updateOccupancycontroller, deleteOccupancycontroller } from "../controllers/occupancyController.js";
import { closeOccupancy, transferOccupancy } from "../controllers/occupancyController.js";
import { createOccupancySchema } from "../validations/occupancyValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getOccupancycontrollers)
  .post(validate(createOccupancySchema), createOccupancycontroller);

router.route("/:id").get(getOccupancycontroller).patch(updateOccupancycontroller).delete(deleteOccupancycontroller);

router.post("/:id/close", closeOccupancy);
router.post("/:id/transfer", transferOccupancy);
export default router;
