// Auto-generated by routeGen.py — pgs routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getPgcontrollers, createPgcontroller, getPgcontroller, updatePgcontroller, deletePgcontroller } from "../controllers/pgController.js";
import { getRoomsByPg, createRoomForPg } from "../controllers/roomController.js";
import { createRoomSchema } from "../validations/roomValidation.js";
import { createPgSchema } from "../validations/pgValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getPgcontrollers)
  .post(validate(createPgSchema), createPgcontroller);

router.route("/:id").get(getPgcontroller).patch(updatePgcontroller).delete(deletePgcontroller);

router.get("/:pgId/rooms", getRoomsByPg);
router.post("/:pgId/rooms", validate(createRoomSchema), createRoomForPg);
export default router;
