// Auto-generated by routeGen.py — reports routes
import express from "express";
import { protect } from "../middlewares/auth.js";
import { arrearsReport, occupancyRateReport, revenueReport } from "../controllers/reportController.js";

const router = express.Router();
router.use(protect);

router.get("/arrears", arrearsReport);                 // ?pgId=&asOf=YYYY-MM-DD
router.get("/occupancy-rate", occupancyRateReport);    // ?pgId=&from=&to=
router.get("/revenue", revenueReport);                 // ?pgId=&from=&to=&groupBy=month|pg|room

export default router;
