// Auto-generated by routeGen.py — rooms routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getRoomcontrollers, createRoomcontroller, getRoomcontroller, updateRoomcontroller, deleteRoomcontroller } from "../controllers/roomController.js";
import { getBedsByRoom, createBedForRoom } from "../controllers/bedController.js";
import { createBedSchema } from "../validations/bedValidation.js";
import { createRoomSchema } from "../validations/roomValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getRoomcontrollers)
  .post(validate(createRoomSchema), createRoomcontroller);

router.route("/:id").get(getRoomcontroller).patch(updateRoomcontroller).delete(deleteRoomcontroller);

router.get("/:id/beds", getBedsByRoom);
router.post("/:id/beds", validate(createBedSchema), createBedForRoom);
export default router;
