// Auto-generated by routeGen.py — search routes
import express from "express";
import { protect } from "../middlewares/auth.js";
import { globalSearch } from "../controllers/searchController.js";

const router = express.Router();
router.use(protect);

router.get("/", globalSearch); // /search?q=...

export default router;
