// Auto-generated by routeGen.py — tenantDocuments routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";
import {
  getTenantDocuments,
  linkTenantDocument,
  unlinkTenantDocument
} from "../controllers/tenantDocumentController.js";
import { linkTenantDocumentSchema } from "../validations/tenantDocumentValidation.js";

const router = express.Router();

// 🔒 Protect all routes
router.use(protect);

// list by tenant
router.get("/", getTenantDocuments);

// link/unlink
router.post("/", validate(linkTenantDocumentSchema), linkTenantDocument);
router.delete("/:tenantId/:docId", unlinkTenantDocument);

export default router;
