// Auto-generated by routeGen.py — tenants routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getTenantcontrollers, createTenantcontroller, getTenantcontroller, updateTenantcontroller, deleteTenantcontroller } from "../controllers/tenantController.js";
import { getTenantOccupancies } from "../controllers/occupancyController.js";
import { getTenantBills } from "../controllers/billController.js";
import { getTenantTransactions } from "../controllers/transactionController.js";
import { getTenantDocuments } from "../controllers/tenantDocumentController.js";
import { createTenantSchema } from "../validations/tenantValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getTenantcontrollers)
  .post(validate(createTenantSchema), createTenantcontroller);

router.route("/:id").get(getTenantcontroller).patch(updateTenantcontroller).delete(deleteTenantcontroller);

router.get("/:id/occupancies", getTenantOccupancies);
router.get("/:id/bills", getTenantBills);
router.get("/:id/transactions", getTenantTransactions);
router.get("/:id/documents", getTenantDocuments);
export default router;
