// Auto-generated by routeGen.py — transactions routes
// Feel free to edit as needed.
import express from "express";
import { protect } from "../middlewares/auth.js";
import { validate } from "../middlewares/validator.js";

import { getTransactioncontrollers, createTransactioncontroller, getTransactioncontroller, updateTransactioncontroller, deleteTransactioncontroller } from "../controllers/transactionController.js";
import { createTransactionSchema } from "../validations/transactionValidation.js";

const router = express.Router();
// 🔒 Protect all routes below
router.use(protect);

router.route("/").get(getTransactioncontrollers)
  .post(validate(createTransactionSchema), createTransactioncontroller);

router.route("/:id").get(getTransactioncontroller).patch(updateTransactioncontroller).delete(deleteTransactioncontroller);

export default router;
